[package]
name = "nbt-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fastnbt = "2.4.4"

[features]
default = []
debug = []
core_debug = ["debug"]
