[package]
name = "shen-nbt2"
version = "0.1.0"
edition = "2021"

[features]
default = []
internal_opt = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
debug = true